name: learning_english_ai
description: Aplicación para aprender inglés con IA

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # BLoC
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  equatable: ^2.0.5

  # Firebase
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.1
  google_sign_in: ^6.1.5
  cloud_firestore: ^4.8.3

  # IA y voz
  speech_to_text: ^7.1.0
  text_to_speech: ^0.2.3
  http: ^1.4.0

  # Utilidades
  get_it: ^7.6.4
  injectable: ^2.1.1
  dartz: ^0.10.1
  intl: ^0.18.1
  flutter_tts: ^4.2.3
  shared_preferences: ^2.2.1
  flutter_dotenv: ^5.1.0
  freezed_annotation: ^2.4.4
  auto_route: ^7.8.4
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.14
  freezed: ^2.5.7
  injectable_generator: ^2.1.3
  auto_route_generator: ^7.2.0