// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4nmb_JuHnruB8YOP7MBSP6yLG0aBH9Ns',
    appId: '1:955678353886:web:5e11823a48d42bba70554f',
    messagingSenderId: '955678353886',
    projectId: 'learningenglishai-3c6d7',
    authDomain: 'learningenglishai-3c6d7.firebaseapp.com',
    storageBucket: 'learningenglishai-3c6d7.firebasestorage.app',
    measurementId: 'G-95H1HVWM9X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTMhUvqrtIk31NW58_JRXXjkVNjNDKOzE',
    appId: '1:955678353886:android:8fab21bc6775874570554f',
    messagingSenderId: '955678353886',
    projectId: 'learningenglishai-3c6d7',
    storageBucket: 'learningenglishai-3c6d7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCEhnHzVowFGmj6wmY6UO1MsYBJNfxEng',
    appId: '1:955678353886:ios:0cb27496120cf9a670554f',
    messagingSenderId: '955678353886',
    projectId: 'learningenglishai-3c6d7',
    storageBucket: 'learningenglishai-3c6d7.firebasestorage.app',
    iosClientId: '955678353886-c3i72956drchv95r8m9bj24itb6a6iv5.apps.googleusercontent.com',
    iosBundleId: 'com.example.learningEnglishAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCEhnHzVowFGmj6wmY6UO1MsYBJNfxEng',
    appId: '1:955678353886:ios:0cb27496120cf9a670554f',
    messagingSenderId: '955678353886',
    projectId: 'learningenglishai-3c6d7',
    storageBucket: 'learningenglishai-3c6d7.firebasestorage.app',
    iosClientId: '955678353886-c3i72956drchv95r8m9bj24itb6a6iv5.apps.googleusercontent.com',
    iosBundleId: 'com.example.learningEnglishAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4nmb_JuHnruB8YOP7MBSP6yLG0aBH9Ns',
    appId: '1:955678353886:web:5a9a539c7c59a35070554f',
    messagingSenderId: '955678353886',
    projectId: 'learningenglishai-3c6d7',
    authDomain: 'learningenglishai-3c6d7.firebaseapp.com',
    storageBucket: 'learningenglishai-3c6d7.firebasestorage.app',
    measurementId: 'G-ZP5Y4RPYCY',
  );
}
